rtspserver: Fix build error
It fixes build error due to breaking changes of rtspdefs introduces
since da2769952abeb86a95018565db96d6c76ab5526a commit

 ../subprojects/gst-rtsp-server/gst/rtsp-server/rtsp-auth.c
../subprojects/gst-rtsp-server/gst/rtsp-server/rtsp-auth.c: In function ‘default_digest_auth’:
../subprojects/gst-rtsp-server/gst/rtsp-server/rtsp-auth.c:819:9: error: too few arguments to function ‘gst_rtsp_generate_digest_auth_response’